package com.company.andy.common.event;

public enum DomainEventType {
    EQUIPMENT_CREATED_EVENT,
    EQUIPMENT_DELETED_EVENT,
    EQUIPMENT_NAME_UPDATED_EVENT,
    EQUIPMENT_HOLDER_UPDATED_EVENT,
    EQUIPMENT_STATUS_UPDATED_EVENT,
    MAINTENANCE_RECORD_CREATED_EVENT,
    MAINTENANCE_RECORD_DELETED_EVENT,
    DEMO_RESERVATION_CREATED_EVENT,
    SYSTEM_BASE_SETTINGS_UPDATED_EVENT,
}
