package com.company.andy.support.testid;

import jakarta.servlet.FilterChain;
import jakarta.servlet.ServletException;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import org.springframework.http.client.ClientHttpRequestInterceptor;
import org.springframework.stereotype.Component;
import org.springframework.web.filter.OncePerRequestFilter;

import java.io.IOException;

import static com.company.andy.TestFixture.X_TEST_ID;

@Component
public class TestIdFilter extends OncePerRequestFilter {
    @Override
    protected void doFilterInternal(
            HttpServletRequest request,
            HttpServletResponse response,
            FilterChain filterChain)
            throws ServletException, IOException {
        TestIdContext.setTestId(request.getHeader(X_TEST_ID));
        try {
            filterChain.doFilter(request, response);
        } finally {
            TestIdContext.clear();
        }
    }

    // pass the testId to every API call,
    // a new testId is generated by TestIdExtension for every test
    public static ClientHttpRequestInterceptor testIdInterceptor() {
        return (request, body, execution) -> {
            String testId = TestIdContext.getTestId();
            if (testId != null) {
                request.getHeaders().set(X_TEST_ID, testId);
            }
            return execution.execute(request, body);
        };
    }

}